admin3:
  events:
    "[tech.wetech.admin3.sys.event.UserLoggedIn]":
      text: "User Login"
      log-template: " {{userinfo.username}} logged in, IP: {{ip}}"
    "[tech.wetech.admin3.sys.event.UserLoggedOut]":
      text: "Logout"
      log-template: " {{userinfo.username}} logged out"
    "[tech.wetech.admin3.sys.event.UserCreated]":
      text: "Create User"
      log-template: "User {{user.username}} created, User ID: {{user.id}}"
    "[tech.wetech.admin3.sys.event.UserUpdated]":
      text: "Update User"
      log-template: "User {{user.username}} updated, User ID: {{user.id}}"
    "[tech.wetech.admin3.sys.event.UserDeleted]":
      text: "Delete User"
      log-template: "User {{user.username}} deleted, User ID: {{user.id}}"
    "[tech.wetech.admin3.sys.event.OrganizationCreated]":
      text: "Create Organization"
      log-template: "Organization node {{organization.name}} created"
    "[tech.wetech.admin3.sys.event.OrganizationUpdated]":
      text: "Update Organization"
      log-template: "Organization node {{organization.name}} updated"
    "[tech.wetech.admin3.sys.event.OrganizationDeleted]":
      text: "Delete Organization"
      log-template: "Organization node {{organization.name}} deleted"
    "[tech.wetech.admin3.sys.event.RoleCreated]":
      text: "Create Role"
      log-template: "Role {{role.name}} created"
    "[tech.wetech.admin3.sys.event.RoleUpdated]":
      text: "Update Role"
      log-template: "Role {{role.name}} updated"
    "[tech.wetech.admin3.sys.event.RoleDeleted]":
      text: "Delete Role"
      log-template: "Role {{role.name}} deleted"
    "[tech.wetech.admin3.sys.event.ResourceCreated]":
      text: "Create Resource"
      log-template: "Resource {{resource.name}} created"
    "[tech.wetech.admin3.sys.event.ResourceUpdated]":
      text: "Update Resource"
      log-template: "Resource {{resource.name}} updated"
    "[tech.wetech.admin3.sys.event.ResourceDeleted]":
      text: "Delete Resource"
      log-template: "Resource {{resource.name}} deleted successfully"
    "[tech.wetech.admin3.sys.event.StorageConfigCreated]":
      text: "Create Object Storage Config"
      log-template: "Object storage config {{config.storageId}} created"
    "[tech.wetech.admin3.sys.event.StorageConfigUpdated]":
      text: "Update Object Storage"
      log-template: "Object storage config {{config.storageId}} updated"
    "[tech.wetech.admin3.sys.event.StorageConfigDeleted]":
      text: "Delete Object Storage Config"
      log-template: "Object storage config {{config.storageId}} deleted successfully"
    "[tech.wetech.admin3.sys.event.StorageConfigMarkedAsDefault]":
      text: "Mark Default Object Storage"
      log-template: "Object storage config {{config.storageId}} marked as default storage location"
